spring:
  datasource:
    name: baicells
    url: jdbc:mysql://172.17.0.3:3306/baicells?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true #url
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port:
    8080
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.baicells.camera.Entity